### ISSUE TITLE
Remove total salary and add Net Tax Liability from Homepage

### ISSUE THREAD

**Issue by Prasu9999** [SamratBogati/Tax_Calculator#5]
the total salary does not shows the the true requirement rather than that add Net tax liability section for monthly and yearly 
![Capture](https://user-images.githubusercontent.com/81411374/118249376-17748000-b4c5-11eb-986d-95e0469bd654.PNG)

**Comment by SamratBogati** [comment]
Ok, @Prasu9999  we will look after that.

**Comment by np03a190078bibhushanthapa** [comment]
Ok, @SamratBogati  please look in to that.  If you need help, you can contact me.

**Comment by Aryan344** [comment]
okay we are still working on it @Prasu9999 @np03a190078bibhushanthapa @SamratBogati @Sandesh612

**Comment by Sandesh612** [comment]
We are still looking at it. Thank you
