### ISSUE TITLE
Net Tax Liability(Yearly) shows Please enter a valid value when calculating the monthly value. It should not be shown.

### ISSUE THREAD

**Issue by np03a190078bibhushanthapa** [SamratBogati/Tax_Calculator#6]
![image](https://user-images.githubusercontent.com/81398939/118346869-6e7a6380-b55e-11eb-98f2-37346ac4d683.png)

**Comment by np03a190078bibhushanthapa** [comment]
Please try to fix this issue as soon as possible. I will also look into this.

**Comment by Prasu9999** [comment]
Me and @SamratBogati  are working on it

**Comment by SamratBogati** [comment]
@np03a190078bibhushanthapa  Thanks for letting me know!

**Comment by SamratBogati** [comment]
I have fixed this in c030c85
